[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vercel-sdk"
version = "0.0.2"
description = "Python SDK for Vercel"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.7.0",
    "anyio>=4.0.0",
    "python-dotenv"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.5.0",
    "pytest>=7.0.0",
    "build",
    "twine",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["vercel*"]
namespaces = true

[tool.setuptools]
include-package-data = false
