[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vercel"
version = "0.3.1"
description = "Python SDK for Vercel"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE", "LICENSE.*"]
dependencies = [
    "vercel-sandbox>=0.0.2",
    "httpx>=0.27.0",
    "pydantic>=2.7.0",
    "anyio>=4.0.0",
    "python-dotenv"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.5.0",
    "pytest>=7.0.0",
    "pytest-asyncio",
    "mypy",
    "build",
    "twine",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["vercel*"]
namespaces = true

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
vercel = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
asyncio_mode = "auto"

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 100
